#!/bin/bash

./analyser add -u "http://www.onvista.de/aktien/Volkswagen-ST-Aktie-DE0007664005" -d "http://www.finanzen.net/termine/Volkswagen" "VOW.DE"
./analyser add -u "http://www.onvista.de/aktien/Siemens-Aktie-DE0007236101" -d "http://www.finanzen.net/termine/Siemens" "SIE.DE"
./analyser add -u "http://www.onvista.de/aktien/Henkel-Aktie-DE0006048432" -d "http://www.finanzen.net/termine/Henkel_vz" "HEN3.DE"
./analyser add -u "http://www.onvista.de/aktien/Infineon-Aktie-DE0006231004" -d "http://www.finanzen.net/termine/Infineon" "IFX.DE"
./analyser add -u "http://www.onvista.de/aktien/Linde-Aktie-DE0006483001" -d "http://www.finanzen.net/termine/Linde" "LIN.DE"
./analyser add -u "http://www.onvista.de/aktien/Merck-Aktie-DE0006599905" -d "http://www.finanzen.net/termine/Merck" "MRK.DE"
./analyser add -u "http://www.onvista.de/aktien/ProSiebenSat-1-Media-Aktie-DE000PSM7770" -d "http://www.finanzen.net/termine/ProSiebenSat1_Media" "PSM.DE"
./analyser add -u "http://www.onvista.de/aktien/RWE-Aktie-DE0007037129" -d "http://www.finanzen.net/termine/RWE" "RWE.DE"
./analyser add -u "http://www.onvista.de/aktien/SAP-Aktie-DE0007164600" -d "http://www.finanzen.net/termine/SAP" "SAP.DE"
./analyser add -u "http://www.onvista.de/aktien/ThyssenKrupp-Aktie-DE0007500001" -d "http://www.finanzen.net/termine/thyssenkrupp" "TKA.DE"
./analyser add -u "http://www.onvista.de/aktien/Vonovia-Aktie-DE000A1ML7J1" -d "http://www.finanzen.net/termine/Vonovia" "VNA.DE"
./analyser add -u "http://www.onvista.de/aktien/HeidelbergCement-Aktie-DE0006047004" -d "http://www.finanzen.net/termine/HeidelbergCement" "HEI.DE" 
./analyser add -u "http://www.onvista.de/aktien/Fresenius-Aktie-DE0005785604" -d "http://www.finanzen.net/termine/Fresenius" "FRE.DE"
./analyser add -u "http://www.onvista.de/aktien/Fresenius-Medical-Care-Aktie-DE0005785802" -d "http://www.finanzen.net/termine/Fresenius_Medical_Care" "FME.DE"
./analyser add -u "http://www.onvista.de/aktien/EON-Aktie-DE000ENAG999" -d "http://www.finanzen.net/termine/EON" "EOAN.DE"
./analyser add -u "http://www.onvista.de/aktien/Deutsche-Telekom-Aktie-DE0005557508" -d "http://www.finanzen.net/termine/Deutsche_Telekom" "DTE.DE"
./analyser add -u "http://www.onvista.de/aktien/Deutsche-Post-Aktie-DE0005552004" -d "http://www.finanzen.net/termine/Deutsche_Post" "DPW.DE"
./analyser add -u "http://www.onvista.de/aktien/Lufthansa-Aktie-DE0008232125" -d "http://www.finanzen.net/termine/Lufthansa" "LHA.DE"
./analyser add -u "http://www.onvista.de/aktien/Daimler-Aktie-DE0007100000" -d "http://www.finanzen.net/termine/Daimler" "DAI.DE"
./analyser add -u "http://www.onvista.de/aktien/Continental-Aktie-DE0005439004" -d "http://www.finanzen.net/termine/Continental" "CON.DE"
./analyser add -u "http://www.onvista.de/aktien/Beiersdorf-Aktie-DE0005200000" -d "http://www.finanzen.net/termine/Beiersdorf" "BEI.DE"
./analyser add -u "http://www.onvista.de/aktien/BMW-Aktie-DE0005190003" -d "http://www.finanzen.net/termine/BMW" "BMW.DE"
./analyser add -u "http://www.onvista.de/aktien/Bayer-Aktie-DE000BAY0017" -d "http://www.finanzen.net/termine/Bayer" "BAYN.DE"
./analyser add -u "http://www.onvista.de/aktien/BASF-Aktie-DE000BASF111" -d "http://www.finanzen.net/termine/BASF" "BAS.DE"
./analyser add -u "http://www.onvista.de/aktien/Adidas-Aktie-DE000A1EWWW0" -d "http://www.finanzen.net/termine/Adidas" "ADS.DE"

# Finanzwerte, benötigen sonderregeln in der Levermann Analyse:
./analyser add -u "http://www.onvista.de/aktien/Muenchener-Rueck-Aktie-DE0008430026" -d "07.02.2017" "MUV2.DE"
./analyser add -u "http://www.onvista.de/aktien/DEUTSCHE-BOERSE-AG-Aktie-DE000A2AA253"
./analyser add -u "http://www.onvista.de/aktien/Deutsche-Bank-Aktie-DE0005140008"
./analyser add -u "http://www.onvista.de/aktien/Commerzbank-Aktie-DE000CBK1001"
./analyser add -u "http://www.onvista.de/aktien/Allianz-Aktie-DE0008404005" -d "11.11.2016" "ALV.DE"
